[theme]
primaryColor = "#2E2E2E"  # Customize primary color (buttons, highlights)
backgroundColor = "white"  # Customize background color (main background)
secondaryBackgroundColor = "#1C1C1C"  # Customize background color for sidebar or secondary areas
textColor = "#A9A9A9"  # Customize text color
font = "sans serif"
